unbound_net_hosts:
- hostname: nft-pve1
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.10
  ipv6: 2001:470:892d:30:0:ffff:c0a8:300a
  description: nft-pve1
- hostname: imm-nft-pve1
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.17
  ipv6: 2001:470:892d:30:0:ffff:c0a8:3011
  description: IMM-nft-pve1
- hostname: imm-usb-nft-pve1
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.18
  ipv6: 2001:470:892d:30:0:ffff:c0a8:3012
  description: IMM_USB-nft-pve1
- hostname: imm-os-nft-pve1
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.19
  ipv6: 2001:470:892d:30:0:ffff:c0a8:3013
  description: IMM_OS-nft-pve1
- hostname: nft-pve2
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.20
  ipv6: 2001:470:892d:30:0:ffff:c0a8:3014
  description: nft-pve2
- hostname: imm-nft-pve2
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.27
  ipv6: 2001:470:892d:30:0:ffff:c0a8:301b
  description: IMM-nft-pve2
- hostname: imm-usb-nft-pve2
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.28
  ipv6: 2001:470:892d:30:0:ffff:c0a8:301c
  description: IMM_USB-nft-pve2
- hostname: imm-os-nft-pve2
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.29
  ipv6: 2001:470:892d:30:0:ffff:c0a8:301d
  description: IMM_OS-nft-pve2
- hostname: idrac-nft-pve3
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.37
  ipv6: 2001:470:892d:30:0:ffff:c0a8:3025
  description: iDRAC-nft-pve3
- hostname: nft-pve3
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.30
  ipv6: 2001:470:892d:30:0:ffff:c0a8:301e
  description: nft-pve3
- hostname: idrac-nft-pve4
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.47
  ipv6: 2001:470:892d:30:0:ffff:c0a8:302f
  description: iDRAC-nft-pve4
- hostname: nft-pve4
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.40
  ipv6: 2001:470:892d:30:0:ffff:c0a8:3028
  description: nft-pve4
- hostname: idrac-nft-pve5
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.57
  ipv6: 2001:470:892d:30:0:ffff:c0a8:3039
  description: iDRAC-nft-pve5
- hostname: nft-pve5
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.50
  ipv6: 2001:470:892d:30:0:ffff:c0a8:3032
  description: nft-pve5
- hostname: idrac-nft-pve6
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.67
  ipv6: 2001:470:892d:30:0:ffff:c0a8:3043
  description: iDRAC-nft-pve6
- hostname: nft-pve6
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.60
  ipv6: 2001:470:892d:30:0:ffff:c0a8:303c
  description: nft-pve6
- hostname: auto-homebridge-wired
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.200
  ipv6: 2001:470:892d:30:0:ffff:c0a8:30c8
  description: auto-Homebridge-Wired
- hostname: auto-homebridge-wifi
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.201
  ipv6: 2001:470:892d:30:0:ffff:c0a8:30c9
  description: auto-Homebridge-WiFi
- hostname: auto-homeassistant-wired
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.202
  ipv6: 2001:470:892d:30:0:ffff:c0a8:30ca
  description: auto-HomeAssistant-Wired
- hostname: auto-homeassistant-wifi
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.203
  ipv6: 2001:470:892d:30:0:ffff:c0a8:30cb
  description: auto-HomeAssistant-WiFi
- hostname: nft-pc-mini-wired
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.204
  ipv6: 2001:470:892d:30:0:ffff:c0a8:30cc
  description: nft-pc-mini-wired
- hostname: nft-pc-mini-wifi
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.205
  ipv6: 2001:470:892d:30:0:ffff:c0a8:30cd
  description: nft-pc-mini-wifi
- hostname: nft-nas1
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.210
  ipv6: 2001:470:892d:30:0:ffff:c0a8:30d2
  description: nft-nas1
- hostname: nft-nas2
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.211
  ipv6: 2001:470:892d:30:0:ffff:c0a8:30d3
  description: nft-nas2
- hostname: nft-nas3
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.212
  ipv6: 2001:470:892d:30:0:ffff:c0a8:30d4
  description: nft-nas3
- hostname: nft-sw01
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.90
  ipv6: 2001:470:892d:30:0:ffff:c0a8:305a
  description: nft-sw01
- hostname: nft-sw01-v20
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.90
  ipv6: 2001:470:892d:34:0:ffff:c0a8:345a
  description: nft-sw01.20
- hostname: nft-sw02
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.91
  ipv6: 2001:470:892d:30:0:ffff:c0a8:305b
  description: nft-sw02
- hostname: nft-sw02-v20
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.91
  ipv6: 2001:470:892d:34:0:ffff:c0a8:345b
  description: nft-sw02.20
- hostname: nft-sw03
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.92
  ipv6: 2001:470:892d:30:0:ffff:c0a8:305c
  description: nft-sw03
- hostname: nft-sw03-v20
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.92
  ipv6: 2001:470:892d:34:0:ffff:c0a8:345c
  description: nft-sw03.20
- hostname: nft-sw03-v30
  domain: netfusiontechnologies.net
  ipv4: 192.168.56.92
  ipv6: 2001:470:892d:38:0:ffff:c0a8:385c
  description: nft-sw03.30
- hostname: nft-sw04
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.93
  ipv6: 2001:470:892d:30:0:ffff:c0a8:305d
  description: nft-sw04
- hostname: nft-sw04-v20
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.93
  ipv6: 2001:470:892d:34:0:ffff:c0a8:345d
  description: nft-sw04.20
- hostname: nft-sw05
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.94
  ipv6: 2001:470:892d:30:0:ffff:c0a8:305e
  description: nft-sw05
- hostname: nft-sw05-v20
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.94
  ipv6: 2001:470:892d:34:0:ffff:c0a8:345e
  description: nft-sw05.20
- hostname: nft-sw06
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.95
  ipv6: 2001:470:892d:30:0:ffff:c0a8:305f
  description: nft-sw06
- hostname: nft-sw06-v20
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.95
  ipv6: 2001:470:892d:34:0:ffff:c0a8:345f
  description: nft-sw06.20
- hostname: nft-sw10
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.195
  ipv6: 2001:470:892d:30:0:ffff:c0a8:30c3
  description: nft-sw10
- hostname: nft-sw07
  domain: netfusiontechnologies.net
  ipv4: 192.168.51.8
  ipv6: 2001:470:892d:33:0:ffff:c0a8:3308
  description: nft-sw07
- hostname: nft-sw08
  domain: netfusiontechnologies.net
  ipv4: 192.168.51.9
  ipv6: 2001:470:892d:33:0:ffff:c0a8:3309
  description: nft-sw08
- hostname: nft-sw09
  domain: netfusiontechnologies.net
  ipv4: 192.168.51.10
  ipv6: 2001:470:892d:33:0:ffff:c0a8:330a
  description: nft-sw09
- hostname: nft-router2
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.199
  ipv6: 2001:470:892d:30:0:ffff:c0a8:30c7
  description: nft-router2
- hostname: nft-printer1
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.230
  ipv6: 2001:470:892d:30:0:ffff:c0a8:30e6
  description: nft-printer1
- hostname: nft-printer2-wired
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.231
  ipv6: 2001:470:892d:30:0:ffff:c0a8:30e7
  description: nft-printer2-wired
- hostname: nft-printer2-wifi
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.232
  ipv6: 2001:470:892d:30:0:ffff:c0a8:30e8
  description: nft-printer2-wifi
- hostname: nft-pdu1
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.240
  ipv6: 2001:470:892d:30:0:ffff:c0a8:30f0
  description: nft-pdu1
- hostname: nft-pdu2
  domain: netfusiontechnologies.net
  ipv4: 192.168.48.241
  ipv6: 2001:470:892d:30:0:ffff:c0a8:30f1
  description: nft-pdu2
- hostname: auto-homebridge2
  domain: netfusiontechnologies.net
  ipv4: 192.168.49.1
  ipv6: 2001:470:892d:31:0:ffff:c0a8:3101
  description: auto-homebridge2
- hostname: auto-haos2
  domain: netfusiontechnologies.net
  ipv4: 192.168.49.2
  ipv6: 2001:470:892d:31:0:ffff:c0a8:3102
  description: auto-haos2
- hostname: vm-macos
  domain: netfusiontechnologies.net
  ipv4: 192.168.49.3
  ipv6: 2001:470:892d:31:0:ffff:c0a8:3103
  description: vm-macos
- hostname: nft-monitor-wired
  domain: netfusiontechnologies.net
  ipv4: 192.168.50.231
  ipv6: 2001:470:892d:32:0:ffff:c0a8:32e7
  description: nft-monitor-wired
- hostname: nft-monitor-wifi
  domain: netfusiontechnologies.net
  ipv4: 192.168.50.232
  ipv6: 2001:470:892d:32:0:ffff:c0a8:32e8
  description: nft-monitor-wifi
- hostname: nft-monitor1
  domain: netfusiontechnologies.net
  ipv4: 192.168.50.233
  ipv6: 2001:470:892d:32:0:ffff:c0a8:32e9
  description: nft-monitor1
- hostname: nft-monitor2
  domain: netfusiontechnologies.net
  ipv4: 192.168.50.234
  ipv6: 2001:470:892d:32:0:ffff:c0a8:32ea
  description: nft-monitor2
- hostname: nft-imac-alex-wired
  domain: netfusiontechnologies.net
  ipv4: 192.168.50.235
  ipv6: 2001:470:892d:32:0:ffff:c0a8:32eb
  description: nft-imac-alex-wired
- hostname: nft-imac-alex-wifi
  domain: netfusiontechnologies.net
  ipv4: 192.168.50.236
  ipv6: 2001:470:892d:32:0:ffff:c0a8:32ec
  description: nft-imac-alex-wifi
- hostname: vm-bluestar
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.101
  ipv6: 2001:470:892d:34:0:ffff:c0a8:3465
  description: vm-bluestar
- hostname: infra-iredmail
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.102
  ipv6: 2001:470:892d:34:0:ffff:c0a8:3466
  description: infra-iRedMail
- hostname: vm-debian
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.103
  ipv6: 2001:470:892d:34:0:ffff:c0a8:3467
  description: vm-debian
- hostname: app-uisp
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.104
  ipv6: 2001:470:892d:34:0:ffff:c0a8:3468
  description: app-uisp
- hostname: vm-windows11
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.105
  ipv6: 2001:470:892d:34:0:ffff:c0a8:3469
  description: vm-windows11
- hostname: db-postgres
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.202
  ipv6: 2001:470:892d:34:0:ffff:c0a8:34ca
  description: db-postgres
- hostname: svc-prometheus
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.203
  ipv6: 2001:470:892d:34:0:ffff:c0a8:34cb
  description: svc-prometheus
- hostname: svc-prometheus-alertmanager
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.204
  ipv6: 2001:470:892d:34:0:ffff:c0a8:34cc
  description: svc-prometheus-alertmanager
- hostname: infra-apache-tomcat
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.205
  ipv6: 2001:470:892d:34:0:ffff:c0a8:34cd
  description: infra-apache-tomcat
- hostname: db-mariadb
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.206
  ipv6: 2001:470:892d:34:0:ffff:c0a8:34ce
  description: db-mariadb
- hostname: db-mongodb
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.207
  ipv6: 2001:470:892d:34:0:ffff:c0a8:34cf
  description: db-mongodb
- hostname: svc-grafana
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.208
  ipv6: 2001:470:892d:34:0:ffff:c0a8:34d0
  description: svc-grafana
- hostname: app-ninja
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.209
  ipv6: 2001:470:892d:34:0:ffff:c0a8:34d1
  description: app-ninja
- hostname: app-omada
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.210
  ipv6: 2001:470:892d:34:0:ffff:c0a8:34d2
  description: app-omada
- hostname: app-odoo
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.211
  ipv6: 2001:470:892d:34:0:ffff:c0a8:34d3
  description: aoo-odoo
- hostname: app-wordpress
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.212
  ipv6: 2001:470:892d:34:0:ffff:c0a8:34d4
  description: app-wordpress
- hostname: app-unifi
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.213
  ipv6: 2001:470:892d:34:0:ffff:c0a8:34d5
  description: app-unifi
- hostname: svc-loki
  domain: netfusiontechnologies.net
  ipv4: 192.168.52.214
  ipv6: 2001:470:892d:34:0:ffff:c0a8:34d6
  description: svc-loki
