- name: rebuild sasl map
  ansible.builtin.command: "postmap {{ sysalerts_postfix_map_type }}:/etc/postfix/sasl_passwd"

- name: rebuild sender canonical map
  ansible.builtin.command: "postmap {{ sysalerts_postfix_map_type }}:/etc/postfix/sender_canonical"

- name: run newaliases
  ansible.builtin.command: newaliases

- name: restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
    enabled: true

