---
- name: Stop on unsupported hosts
  ansible.builtin.meta: end_host
  when: ansible_os_family not in ["Debian", "Archlinux"]

- name: Install node exporter on Debian
  ansible.builtin.apt:
    name:
      - "{{ node_exporter_package_name_debian }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install node exporter on Arch
  community.general.pacman:
    name:
      - "{{ node_exporter_package_name_arch }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Archlinux"

- name: Ensure node exporter service enabled and started on Debian
  ansible.builtin.service:
    name: "{{ node_exporter_service_name_debian }}"
    state: started
    enabled: true
  when: ansible_os_family == "Debian"

- name: Ensure node exporter service enabled and started on Arch
  ansible.builtin.service:
    name: "{{ node_exporter_service_name_arch }}"
    state: started
    enabled: true
  when: ansible_os_family == "Archlinux"
