---
mktxp_group_name: prometheus
mktxp_group_policy: "read,api"

mktxp_user_name: mktxp
mktxp_user_password: "{{ vault_mktxp_password }}"
mktxp_user_allowed_address: "192.168.48.231/32"

mktxp_api_service: api
mktxp_api_port: 8728

# RouterOS API login settings.
# By default, reuse the existing inventory ansible_user and ansible password/vault.
routeros_api_hostname: "{{ ansible_host }}"
routeros_api_username: "{{ ansible_user }}"
routeros_api_password: "{{ vault_routeros_ansible_password }}"
routeros_api_tls: false
routeros_api_validate_certs: false
