all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_pythin_interpreter: /usr/bin/python3

  children:
    managed_linux:
      children:
        proxmox_nodes:
        lxc:
        qemu_linux:
        infra_servers:

    managed_ssh_special:
      children:
        macos_hosts:
        opnsense:
        appliances:

    managed_windows:
      children:
        windows_hosts:

    static_devices:
      children:
        infra_servers:
        network_switches:
        nas_python:
        nas_raw:
        printers:
        power_devices:

    proxmox_nodes:
      hosts:
        nft-pve1:
          ansible_host: 192.168.48.10
        nft-pve2:
          ansible_host: 192.168.48.20
        nft-pve3:
          ansible_host: 192.168.48.30
        nft-pve3a:
          ansible_host: 192.168.53.6
        nft-pve4:
          ansible_host: 192.168.48.40
        nft-pve5:
          ansible_host: 192.168.48.50
        nft-pve6:
          ansible_host: 192.168.53.5

    macos_hosts:
      hosts:
        MacOS:
          ansible_host: 192.168.49.3
          ansible_user: ansible
          ansible_python_interpreter: /usr/bin/python3

    windows_hosts:
      hosts:
        ViewPower:
          ansible_host: 192.168.52.105

    opnsense:
      hosts:
        OPNsense:
          ansible_host: 192.168.53.1

    appliances:
      hosts:
        haos_vm:
          ansible_host: haos

        haos_box:
          ansible_host: 192.168.48.202
          device_type: haos
          ssh_available: true

    infra_servers:
      hosts:
        homebridge-static:
          ansible_host: 192.168.48.200
          device_type: ubuntu
          ssh_available: true
        nft-monitor:

    monitoring:
      hosts:
        prometheus:
        prometheus-alertmanager:
        grafana:
        nft-monitor:

    network_switches:
      vars:
        ansible_user: ansible
        ansible_connection: network_cli
      hosts:
        nft-sw01:
          ansible_host: 192.168.48.90
          device_type: mikrotik
          ssh_available: true
        nft-sw02:
          ansible_host: 192.168.48.91
          device_type: mikrotik
          ssh_available: true
        nft-sw03:
          ansible_host: 192.168.48.92
          device_type: mikrotik
          ssh_available: true
        nft-sw04:
          ansible_host: 192.168.48.93
          device_type: mikrotik
          ssh_available: true
        nft-sw05:
          ansible_host: 192.168.48.94
          device_type: mikrotik
          ssh_available: true
        nft-sw06:
          ansible_host: 192.168.48.95
          device_type: mikrotik
          ssh_available: true

    nas_python:
      hosts:
        nft-nas1:
          ansible_host: 192.168.48.210
          device_type: synology
          ssh_available: false
        nft-nas2:
          ansible_host: 192.168.48.211
          device_type: synology
          ssh_available: true

    nas_raw:
      hosts:
        nft-nas3:
          ansible_host: 192.168.48.212
          device_type: qnap
          ssh_available: true
          ansible_python_interpreter: /share/MD0_DATA/.qpkg/Python3/python3/bin/python3

    printers:
      hosts:
        nft-printer1:
          ansible_host: 192.168.48.230
          ssh_available: false
        nft-printer2:
          ansible_host: 192.168.48.231
          ssh_available: false

    power_devices:
      hosts:
        nft-pdu1:
          ansible_host: 192.168.48.240
          ssh_available: false
        nft-pdu2:
          ansible_host: 192.168.48.241
          ssh_available: false
