pve_exporter_user: pve-exporter
pve_exporter_group: pve-exporter
pve_exporter_config_dir: /etc/prometheus-pve-exporter
pve_exporter_config_file: /etc/prometheus-pve-exporter/pve.yml
pve_exporter_home: /var/lib/prometheus-pve-exporter
pve_exporter_listen_address: "[::]:9221"

pve_exporter_venv: /opt/prometheus-pve-exporter
pve_exporter_install_method: pip
pve_exporter_pip_executable: python3 -m pip
pve_exporter_package_name: prometheus-pve-exporter

pve_exporter_collectors:
  - --collector.status
  - --collector.version
  - --collector.node
  - --collector.cluster
  - --collector.resources
  - --collector.backup-info
  - --collector.replication
  - --collector.subscription
  - --collector.pve-api-metrics
  - --collector.target-metrics

pve_exporter_modules:
  default:
    verify_ssl: false
    user: "{{ pve_exporter_api_user }}"
    password: "{{ pve_exporter_api_password }}"

