---
- name: Create MKTXP group and user on MikroTik devices
  hosts: network_switches
  gather_facts: false
  collections:
    - community.routeros

  roles:
    - role: netfusion.routeros.mikrotik_mktxp_user
